FROM node:16.13.2-slim

WORKDIR /frontend

ENV SHELL=/bin/sh LANG=en_US.UTF-8

RUN apt-get update && \
  apt-get install -y \
  wget \
  net-tools \
  build-essential

COPY package.json /frontend/
COPY yarn.lock /frontend/

RUN yarn install --frozen-lockfile && \
  yarn cache clean

COPY . /frontend/

RUN yarn build
CMD yarn start
