# Generated by Django 4.2.4 on 2023-08-20 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="is_done",
            new_name="is_deleted",
        ),
    ]
