# Generated by Django 4.1.2 on 2022-12-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="posted_at",
            new_name="published_at",
        ),
    ]
